interface Props {
  data?: {
    severity?: string;
    congestion_score?: number;
    constables?: number;
    diversion?: string;
    event_cause?: string;
    zone?: string;
    decision_factors?: string[];
  };
}

export default function AIOperationsBrief({ data }: Props) {
  const severityColor =
    data?.severity === "Critical"
      ? "text-red-400"
      : data?.severity === "High"
        ? "text-orange-400"
        : data?.severity === "Medium"
          ? "text-yellow-400"
          : "text-green-400";

  return (
    <div className="h-full rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-6 shadow-xl">
      {/* HEADER */}

      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold text-white">
            AI Operations Summary
          </h2>

          <p className="text-xs text-slate-400 mt-1">
            Generated by ETIS Intelligence Engine
          </p>
        </div>

        <div className="h-3 w-3 rounded-full bg-green-500 animate-pulse" />
      </div>

      {/* INCIDENT */}

      <div className="bg-slate-800/60 rounded-2xl p-4 border border-slate-700 mb-4">
        <p className="text-xs text-slate-400 mb-1">INCIDENT TYPE</p>

        <h3 className="text-lg font-semibold capitalize">
          {data?.event_cause || "Unknown Incident"}
        </h3>

        <p className="text-sm text-slate-500 mt-1">
          {data?.zone || "Unknown Zone"}
        </p>
      </div>

      {/* METRICS */}

      <div className="grid grid-cols-2 gap-3">
        <div className="bg-slate-800/50 rounded-xl p-4">
          <p className="text-xs text-slate-400">Severity</p>

          <h3 className={`text-xl font-bold mt-1 ${severityColor}`}>
            {data?.severity || "--"}
          </h3>
        </div>

        <div className="bg-slate-800/50 rounded-xl p-4">
          <p className="text-xs text-slate-400">Congestion</p>

          <h3 className="text-xl font-bold text-white mt-1">
            {data?.congestion_score ?? "--"}%
          </h3>
        </div>

        <div className="bg-slate-800/50 rounded-xl p-4">
          <p className="text-xs text-slate-400">Constables</p>

          <h3 className="text-xl font-bold text-cyan-400 mt-1">
            {data?.constables ?? "--"}
          </h3>
        </div>

        <div className="bg-slate-800/50 rounded-xl p-4">
          <p className="text-xs text-slate-400">Diversion</p>

          <h3 className="text-xl font-bold text-purple-400 mt-1">
            {data?.diversion || "--"}
          </h3>
        </div>
      </div>

      {/* AI REASONING */}

      <div className="mt-5">
        <h3 className="font-semibold mb-3">Why ETIS Recommended This</h3>

        <div className="space-y-2">
          {data?.decision_factors?.map((factor, index) => (
            <div
              key={index}
              className="bg-slate-800/40 rounded-lg p-3 text-sm text-slate-300"
            >
              • {factor}
            </div>
          ))}
        </div>
      </div>

      {/* ACTION */}

      <div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 p-4">
        <p className="text-xs text-red-300 mb-1">RECOMMENDED ACTION</p>

        <p className="font-semibold text-white">
          Deploy {data?.constables ?? 0} constables and activate{" "}
          {data?.diversion} diversion strategy immediately.
        </p>
      </div>

      {/* FOOTER */}

      <div className="mt-5 border-t border-slate-800 pt-4">
        <p className="text-xs text-slate-500">
          Last updated in real time by ETIS AI Engine
        </p>
      </div>
    </div>
  );
}
