export default function AIRecommendation({ data }: any) {
  return (
    <div className="bg-slate-900 rounded-2xl border border-slate-800 p-5 shadow-xl min-h-[420px]">
      {/* HEADER */}

      <div className="flex justify-between items-center mb-5">
        <div>
          <h2 className="text-xl font-bold">AI Deployment Plan</h2>

          <p className="text-xs text-slate-400">
            Generated by ETIS Intelligence Engine
          </p>
        </div>

        <div className="px-3 py-1 rounded-full bg-green-500/20 text-green-400 text-xs font-semibold">
          ACTIVE
        </div>
      </div>

      {/* RESOURCE GRID */}

      <div className="grid grid-cols-2 gap-3">
        <div className="bg-slate-800 rounded-xl p-4 border border-slate-700">
          <p className="text-xs text-slate-400">Constables</p>

          <h3 className="text-3xl font-bold mt-1">{data.constables}</h3>
        </div>

        <div className="bg-slate-800 rounded-xl p-4 border border-slate-700">
          <p className="text-xs text-slate-400">ASI</p>

          <h3 className="text-3xl font-bold mt-1">{data.asi}</h3>
        </div>

        <div className="bg-slate-800 rounded-xl p-4 border border-slate-700">
          <p className="text-xs text-slate-400">Inspector</p>

          <h3 className="text-3xl font-bold mt-1">{data.inspector}</h3>
        </div>

        <div className="bg-slate-800 rounded-xl p-4 border border-slate-700">
          <p className="text-xs text-slate-400">Barricades</p>

          <h3 className="text-3xl font-bold mt-1">{data.barricades}</h3>
        </div>
      </div>

      {/* ACTION CARD */}

      <div className="mt-4 rounded-xl border border-orange-500/30 bg-orange-500/10 p-4">
        <div className="flex justify-between items-center">
          <div>
            <p className="text-xs text-orange-300">Recommended Diversion</p>

            <h3 className="text-2xl font-bold text-orange-400">
              {data.diversion}
            </h3>
          </div>

          <div className="text-3xl">🚧</div>
        </div>
      </div>

      {/* EXECUTIVE SUMMARY */}

      <div className="mt-4 bg-slate-800 rounded-xl p-4 border border-slate-700">
        <h3 className="font-semibold mb-2">AI Summary</h3>

        <p className="text-sm text-slate-300 leading-relaxed">
          ETIS recommends deployment of
          <span className="font-semibold text-white">
            {" "}
            {data.constables} constables
          </span>
          ,<span className="font-semibold text-white"> {data.asi} ASI</span>,
          and
          <span className="font-semibold text-white">
            {" "}
            {data.inspector} inspector
          </span>
          . Current congestion risk indicates that
          <span className="text-orange-400 font-semibold">
            {" "}
            {data.diversion}
          </span>{" "}
          traffic diversion should be activated.
        </p>
      </div>
    </div>
  );
}
